### ISSUE TITLE
demo-android module missing

### ISSUE THREAD

**Issue by berendjan** [Tribler/kotlin-ipv8#27]
The [Overlay](https://github.com/Tribler/kotlin-ipv8/blob/master/doc/OverlayTutorial.md#project-setup) states an `demo-android` module as an example of how to configure an Android app module, initialize IPv8, and interact with the overlays. Where can I find it? it seems to be missing.
Im trying to run the demo network on an S7/S8 phone and its missing a built configuration.

**Comment by MattSkala** [comment]
Thanks for pointing this out. The Android demo has been moved to [Tribler/trustchain-superapp](https://github.com/Tribler/trustchain-superapp) and the docs has not been updated. However, I agree it's useful to have a simple Android demo here as well, so I added demo-android module in #28 showing how to set up a library and get a list of connected peers. However, for advanced usage and message sending, please check the superapp.
