### ISSUE TITLE
Removing bootstrap peers?

### ISSUE THREAD

**Issue by Tim-W** [Tribler/kotlin-ipv8#32]
What are the steps towards removing the bootstrap peers that are currently hardcoded in this project? Does it require an implementation of a distributed hash table? I can understand it will be much harder to find peers without bootstrap nodes/trackers, but is it possible with the current functionalities? I guess that there needs to be more functionalities and testing for peers to do broadcasting of their identities to find other peers.

**Comment by MattSkala** [comment]
What is your motivation for removing bootstrap peers? You will always need to contact at least one bootstrap server to join the network. When you contact a new peer, an introduction request is first sent to them. The other peer then responds with an introduction response which includes an IP address of a random peer you can connect to. With this mechanism, peer discovery is already distributed. The bootstrap server should be only needed for a bootstrap, to connect to the first peer.

The DHT would be only needed if you want to connect to a specific peer with a specific public key. Right now, introduced peers are selected randomly.
